### PR TITLE
Test for Node 0.8 support

### PR DESCRIPTION
**Pull request by jbnicolai**
Allow node 0.8 to be used, and tested through Travis.

This is to allow mocha to adopt this package, see mochajs/mocha#1545

@sindresorhus you okay with extending support to 0.8?

### CODE REVIEW

**Comment by dasilvacontin** [comment]
@jbnicolai, I think this is more of an `npm` version error, but maybe I'm wrong.

**Comment by jbnicolai** [comment]
@dasilvacontin am I wrong in my understanding [this](https://travis-ci.org/mochajs/mocha/jobs/50164820) stacktrace is not due to node 0.8 not being supported by supports-color?

```bash
npm ERR! Error: No compatible version found: supports-color@'^1.2.0'
npm ERR! Valid install targets:
npm ERR! ["0.2.0","1.0.0","1.1.0","1.2.0"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at RegClient.get_ (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:101:14)
npm ERR!     at RegClient.<anonymous> (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:37:12)
npm ERR!     at fs.readFile (fs.js:181:14)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

**Comment by dasilvacontin** [comment]
I think it's `npm`'s change of behaviour for the `^` char some versions ago.

**Comment by sindresorhus** [comment]
Sure, since Mocha needs it.

But Mocha should seriously consider dropping support for 0.8.

Build fixed in https://github.com/sindresorhus/supports-color/commit/4f4c583d6bca1af987804fb8c37e194ab4a46882

**Comment by dasilvacontin** [comment]
Thanks @sindresorhus! I'll talk with the team about dropping support for 0.8. Any other reason besides the release is over one year old?

**Comment by sindresorhus** [comment]
Node 0.8 was released on June 25, 2012. That's 2 years 8 months. The few people still needing 0.8 support can just stay on the current Mocha version.

**Pull request merged**
